-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-14 18:33:38 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE band (
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    split_year    NUMBER(4),
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE band
    ADD CONSTRAINT band_pk PRIMARY KEY ( band_name,
                                         formed_year,
                                         country_name );

CREATE TABLE band_fan (
    id            INTEGER NOT NULL,
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE band_fan
    ADD CONSTRAINT band_fan_pk PRIMARY KEY ( id,
                                             band_name,
                                             formed_year,
                                             country_name );

CREATE TABLE band_genre (
    genre_name    VARCHAR2(50) NOT NULL,
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE band_genre
    ADD CONSTRAINT band_genre_pk PRIMARY KEY ( genre_name,
                                               band_name,
                                               formed_year,
                                               country_name );

CREATE TABLE country (
    country_name VARCHAR2(50) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_name );

CREATE TABLE fan (
    id        INTEGER NOT NULL,
    fan_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE fan ADD CONSTRAINT fan_pk PRIMARY KEY ( id );

ALTER TABLE fan ADD CONSTRAINT fan_uk UNIQUE ( fan_name );

CREATE TABLE genre (
    genre_name VARCHAR2(50) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_name );

ALTER TABLE band_fan
    ADD CONSTRAINT band_fan_fk1 FOREIGN KEY ( band_name,
                                              formed_year,
                                              country_name )
        REFERENCES band ( band_name,
                          formed_year,
                          country_name );

ALTER TABLE band_fan
    ADD CONSTRAINT band_fan_fk2 FOREIGN KEY ( id )
        REFERENCES fan ( id );

ALTER TABLE band
    ADD CONSTRAINT band_fk FOREIGN KEY ( country_name )
        REFERENCES country ( country_name );

ALTER TABLE band_genre
    ADD CONSTRAINT band_genre_fk1 FOREIGN KEY ( band_name,
                                                formed_year,
                                                country_name )
        REFERENCES band ( band_name,
                          formed_year,
                          country_name );

ALTER TABLE band_genre
    ADD CONSTRAINT band_genre_fk2 FOREIGN KEY ( genre_name )
        REFERENCES genre ( genre_name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

