-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-04 22:14:20 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE bands (
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    split_year    NUMBER(4),
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE bands
    ADD CONSTRAINT bands_pk PRIMARY KEY ( band_name,
                                          formed_year,
                                          country_name );

CREATE TABLE bands_genres (
    genre_name    VARCHAR2(50) NOT NULL,
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE bands_genres
    ADD CONSTRAINT bands_genres_pk PRIMARY KEY ( genre_name,
                                                 band_name,
                                                 formed_year,
                                                 country_name );

CREATE TABLE countries (
    country_name VARCHAR2(50) NOT NULL
);

ALTER TABLE countries ADD CONSTRAINT countries_pk PRIMARY KEY ( country_name );

CREATE TABLE fans (
    record_date   DATE NOT NULL,
    fans          INTEGER,
    band_name     VARCHAR2(50) NOT NULL,
    formed_year   NUMBER(4) NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE fans
    ADD CONSTRAINT fans_pk PRIMARY KEY ( record_date,
                                         band_name,
                                         formed_year,
                                         country_name );

CREATE TABLE genres (
    genre_name VARCHAR2(50) NOT NULL
);

ALTER TABLE genres ADD CONSTRAINT genres_pk PRIMARY KEY ( genre_name );

ALTER TABLE bands
    ADD CONSTRAINT bands_countries_fk FOREIGN KEY ( country_name )
        REFERENCES countries ( country_name );

ALTER TABLE bands_genres
    ADD CONSTRAINT bands_genres_fk1 FOREIGN KEY ( band_name,
                                                  formed_year,
                                                  country_name )
        REFERENCES bands ( band_name,
                           formed_year,
                           country_name );

ALTER TABLE bands_genres
    ADD CONSTRAINT bands_genres_fk2 FOREIGN KEY ( genre_name )
        REFERENCES genres ( genre_name );

ALTER TABLE fans
    ADD CONSTRAINT fans_bands_fk FOREIGN KEY ( band_name,
                                               formed_year,
                                               country_name )
        REFERENCES bands ( band_name,
                           formed_year,
                           country_name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
